name: BarCode

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Build environment'
        type: environment
        default: staging
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout theme repo
      uses: actions/checkout@main
      with:
          repository: Aspose/products.aspose.app
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0 
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.110.0'
          extended: true
    - name: Install autoprefixer
      run:  npm install -D --save autoprefixer
    - name: Install postcss-cli
      run:  npm install -D --save postcss-cli
    - name: Build BarCode
      run: hugo --config "./configs/common.toml","./configs/barcode.toml -c "content/barcode" -b "https://products.aspose.app/barcode" --cleanDestinationDir --minify
    - name: Deploy BarCode to S3
      run: hugo deploy --config "./configs/barcode.toml" --maxDeletes=-1 --target "${{ github.event.inputs.environment }}" --force
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
